name: publish testPyPi

on:
  push:
    tags:
    - v*
jobs:
  build-and-publish-test:
    name: build and publish to test PyPi
    runs-on: ubuntu-22.04
    environment:
      name: testpypi
      url: https://test.pypi.org/p/daphruler
    steps:
    - uses: actions/checkout@v4
    - name: setup python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build binary wheel and source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/


