name: publish testPyPi

on:
  push:
    branches:
    - f-packaged
jobs:
  build-and-publish-test:
    name: build and publish to test PyPi
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: setup python 3.6.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.8
    - name: install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build binary wheel and source tarball
      run: >-
        python -m
        build
        --stdist
        --wheel
        --outdir dist/
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/


